# Generated by Django 4.0.4 on 2022-06-21 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
