# Generated by Django 4.0.4 on 2022-06-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedkata',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.challenge'),
            preserve_default=False,
        ),
    ]
