# Generated by Django 4.0.4 on 2022-06-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_savedkata_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
