# Generated by Django 4.0.4 on 2022-06-03 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_current_kata_alter_challenge_katas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedKata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_code', models.TextField()),
                ('saved_test', models.TextField()),
                ('kata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Kata',
                'verbose_name_plural': 'Saved Katas',
                'ordering': ['-created_at'],
            },
        ),
    ]
