# Generated by Django 4.0.4 on 2022-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_savedkata'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedkata',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedkata',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_kata_index',
            field=models.IntegerField(default=0),
        ),
    ]
